### ISSUE TITLE
Using convertMSFiles

### ISSUE THREAD

**Issue by BaylorSci** [rickhelmus/patRoon#14]
I am working with Waters .raw files and wondered if i could use this to convert from .raw to mzML all in one pipeline. However, i am struggling. I have tried two ways, one where i use the example data to to convert files in the files location substituting thermo for waters. The files have already been centroided using masslynx accuratemass but i have also gotten the raw data and tried to centroid as well with no luck.  I typically get the following error "Error in files[keepFiles] : invalid subscript type 'list'"
The script i have used is as follows presuming that all files in folder will be converted to mzML and put into the centroided folder. 
convertMSFiles(
  files="Data/2-Raw",
  outPath = "Data/Centroided",
  dirs = TRUE,
  from ="waters",
  to = "mzML")

I am obviously missing something. Any help would be greatly appreciated.

**Comment by rickhelmus** [comment]
Hello,

Thanks for the report!

Just to be absolutely sure that I understand the situation well: the raw files files are placed in `<current R working directory>/Data/2-Raw` and are still in .raw format?

Normally the function will check if files are missing or output already exists. Do you see any warning messages related to that?

The error you see is a small bug, which happens if no files at all could be found to be converted. Would it be possible that the file extension is not exactly `.raw`, but eg `.RAW` or `.Raw`? (This shouldn't matter on Windows systems though). I never tried Waters input data myself, so maybe something strange is up with that.

If possible you can send me 1-2 files so I can test myself.

Thanks,
Rick

**Comment by BaylorSci** [comment]
Hello
many thanks for getting back to me. The raw files are indeed placed in the current working directory in Data/2-Raw and are still in .raw format. I did wonder if it was an issue with the files, but successfully converted them using the pwiz programme externally to R. I have tried this with 3 files, individually and together with no luck. I can send you files no problem, however even with compression, the files are too big to attach here. How would you prefer to share? 

These are small tester files which i'm optimizing with prior to running actual project through the pipeline so any help would be appreciated. 
Thanks
L

**Comment by rickhelmus** [comment]
Hello,

Yes maybe it's best if you can send me some of the files. I guess you can use WeTransfer or something similar for that?

**Comment by BaylorSci** [comment]
Perfect. Please find attached the link to two files. I have removed the lockmass function from the files but as I mentioned earlier, they still successfully converted to mzML using the pw GUI.

https://we.tl/t-cUVR7KnBWk

**Comment by rickhelmus** [comment]
Many thanks for the data! It seems that Waters raw files are actually directories. `convertMSFiles()` and related functionality should be able to recognize them as such. (I had to change quite a bit so hopefully nothing broke...)

I was able to convert your files in `patRoon`, but *only* if centroiding is disabled. Otherwise msConvert would throw an exception error. Interestingly, it worked from the ProteoWizard GUI when using `cwt` peakPicking. Sounds to me like a bug in ProteoWizard, perhaps you can file a bug report over there if you also get these problems?

Thanks,
Rick

**Comment by BaylorSci** [comment]
Many thanks. So I presume that I will need to download the latest version of patRoon package. The centroiding being disabled is fine as i have been using the MSNbase package for centroiding of the data. It is unusual that the CWT peakpicking works on the proteowizard GUI but not on the package. Apologies for the question, but if the proteowizard GUI works,, then logically, the bug may be in the package or is that to simple? Could it be the version I am using  and directing patRoon to use?

**Comment by rickhelmus** [comment]
Hello,

False alarm! I made the wrong assumption that `msConvert` by default uses `cwt` unless vendor is specified, but it uses yet another algorithm in this scenario. This algorithm caused the exception I saw earlier.

Anyway, you can now use `centroid="cwt"` as parameter to `convertMSFiles()` and it should convert your files without any errors.

Regards,
Rick

**Comment by rickhelmus** [comment]
Closing this. Please re-open if you still find there are issues.
