### ISSUE TITLE
peak areas altered after conversion and fillChromPeaks()

### ISSUE THREAD

**Issue by stolltho** [rickhelmus/patRoon#26]
Hi Rick

The following is more a question than an issue:
I was wondering if the code below is a valid way to employ the fillChromPeaks() function after featureGrouping and conversion  or is there a more elegant way (incl. reporting)?

Here comes the issue: 
If I run the code seen below and compare peak areas (not of the 'filled' ones) before and after imputation (fGroup vs xdata_filled), suddenly peak areas of all features were altered drastically (x-times larger: 6800 > 142000, 5800 > 163000)!?

I wonder if there is an issue w/ the conversion or fillChromPeaks() function?
Apart from that, the group and retention time column in the exported spreadsheet is also missing.
I can send you a snippet of the spreadsheets if you want.

Cheers,
Thomas

```R
#######################################
### Group and align features between analysis
fGroups <- withOpt(cache.mode="none", groupFeatures(fList, "xcms3", rtalign = TRUE, 
                                                    groupParam = pdp,
                                                    retAlignParam = owp))
### Conversion
xdata <- getXCMSnExp(fGroups)
### Filling missing peak data using the peak area from identified chromatographic peaks
xdata_filled <- fillChromPeaks(xdata, param = ChromPeakAreaParam())

### Reporting xdata
### Extract the feature definitions
ft_def <- featureDefinitions(xdata_filled)
### Get feature information
ft_inf <- featureSummary(xdata_filled, group = xdata_filled$sample_group)
### Get feature abundance
ft_ints <- featureValues(xdata_filled, value = "into")
### Make loop for data export
ft_def_export <- data.frame(ft_def@rownames, ft_def@listData[1])
for(i in 1: (length(ft_def@listData)-1)){
  ft_def_export[,i+1] = ft_def@listData[i]
}

### Export data
ft_def_export <- cbind(ft_def_export, data.frame(ft_ints))
write.csv(ft_def_export, file = "result_xcms_xdata_filled.csv", row.names = FALSE)
```

**Comment by rickhelmus** [comment]
Hi Thomas,

That's an interesting question. It has been a while since I tried imputation with XCMS, so it is possible it goes somewhere wrong. On the other hand, it seems you are continuing with XCMS after `getXCMSnExp()` so if it's on the `patRoon` side I expect it to be the conversion.

Just to clarify:
- when you look at the `fGroups` are you really looking at areas or the peak intensities? By default `as.data.table()`, `reportCSV()` etc all report intensities. You can get the areas with e.g. `as.data.table(fGroups, areas = TRUE)`.
- The peak areas are OK when you skip the imputation step?
- What happens if you re-import the imputed data? (with `importFeatureGroupsXCMS3()`)

PS: I edited your post to fix the code formatting.

**Comment by stolltho** [comment]
Thanks Rick. 
Mystery solved. I was looking at peak intensities before imputation and peak area afterwards. Usually I prefer peak area over peak height. I wasn't aware patRoon exports intensities, I assumed values are peak area. All good.
Cheers,
Thomas

**Comment by rickhelmus** [comment]
Great, glad it worked out.

Thanks,
Rick
