### ISSUE TITLE
findFeatures error

### ISSUE THREAD

**Issue by rachsmo** [rickhelmus/patRoon#30]
Hello Rick, 

I seem to be having an issue with the findFeatures function when applying to my data. I had converted an Agilent .d file externally with MSConvert to mzML. 

Upon attempting to find features I receive this error below: 
![findFeatures error](https://user-images.githubusercontent.com/96398893/146698532-92e29540-1976-4370-9055-a963817c0e9a.png)

This only happens with my own files and not with example data. I have tried cutting the file down in size, etc, but have yet to resolve the issue. Any help is greatly appreciated. 

Thanks, Rachel

**Comment by rickhelmus** [comment]
Hi Rachel,

Thanks for reporting the issue. I have never worked with Agilent data, so not much experience I can share there. The first thing is to check the logs: they should be in the `log/openms` directory inside your project directory. Hopefully you get more error information there. Otherwise, if you don't mind you can also share an analysis file with me so I can try it myself. Ideally this would be the raw file so I can convert it myself.

Thanks,
Rick

**Comment by rachsmo** [comment]
Hi Rick, 

Thank you so much for your quick response. Based on the logs, the file still contained Profile data after conversion and hadn't been centroided. 

-> Error: File empty (the file 'Error: Profile data provided but centroided spectra expected. To enforce processing of the data set the -force flag.' is empty)

After adjusting the parameters in MSConvert (peakpicking -> vendor), I am able to use the FindFeatures function.

Thanks again, 
Rachel
