### ISSUE TITLE
[JOSS Review] Create individual doc page for every function and class in handbook

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#35]
The individual pipeline steps are all documented in a single page ([here](https://rickhelmus.github.io/patRoon/reference/feature-finding.html)), making it very hard do actually understand the parameters, as the section covers all functions. It would be a lot easier if each function actually had its own page and the return value would be the class, and the class having its own documentation page again - I think this would make the documentation a lot better!

**Comment by rickhelmus** [comment]
Hello,

Thanks for bringing this up. The reference documentation has been growing and growing over the years, and I took this issue as a good reason to do some refactoring. 

The workflow data generation functions and their algorithm specific counterparts are now documented in separate pages. Furthermore, I made lots of small textual improvements in the process. For example, the structure is now as follows:
- [findFeatures()](https://rickhelmus.github.io/patRoon/reference/findFeatures.html)
    - [findFeaturesOpenMS()](https://rickhelmus.github.io/patRoon/reference/findFeaturesOpenMS.html)
    - [findFeaturesXCMS3()](https://rickhelmus.github.io/patRoon/reference/findFeaturesXCMS3.html)
    - [findFeaturesKPIC2()](https://rickhelmus.github.io/patRoon/reference/findFeaturesKPIC2.html)
    - ...
- [groupFeatures()](https://rickhelmus.github.io/patRoon/reference/groupFeatures.html)
    - [groupFeaturesOpenMS()](https://rickhelmus.github.io/patRoon/reference/groupFeaturesOpenMS.html)
    - [groupFeaturesXCMS3()](https://rickhelmus.github.io/patRoon/reference/groupFeaturesXCMS3.html)
    - [groupFeaturesKPIC2()](https://rickhelmus.github.io/patRoon/reference/groupFeaturesKPIC2.html)
    - ...
- [generateComponents()](https://rickhelmus.github.io/patRoon/reference/generateComponents.html)
    - [generateComponentsCAMERA()](https://rickhelmus.github.io/patRoon/reference/generateComponentsCAMERA.html)
    - [generateComponentsCliqueMS()](https://rickhelmus.github.io/patRoon/reference/generateComponentsCliqueMS.html)
    - [generateComponentsTPs()](https://rickhelmus.github.io/patRoon/reference/generateComponentsTPs.html)
    - ...
- ...

Note that output classes+their methods were already documented in separate pages (e.g. [features](https://rickhelmus.github.io/patRoon/reference/features-class.html), [components](https://rickhelmus.github.io/patRoon/reference/components-class.html)). Based on other packages it seems common to combine them. However, to reduce the long page length for `featureGroups`, I moved the plotting methods to [their own page](https://rickhelmus.github.io/patRoon/reference/feature-plotting.html).

I just pushed the work to master. Since the commits [are huge and changed a lot of files](https://github.com/rickhelmus/patRoon/compare/15cf10f41b3b60d33e3aa36d86c656e7f02fb586...master), for a comparison it would be probably easier to compare the active website and the one [archived at Zenodo](https://zenodo.org/record/5752071).

**Comment by hechth** [comment]
That sounds amazing! I will have a look at the new pages.
