### ISSUE TITLE
[JOSS Review] State of the field: Do the authors describe how this software compares to other commonly-used packages?

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#40]
The paper lacks a section giving an overview of the field and the actually used methods (short description of BioTransformer). Currently, this is somewhat addressed with Table 1 and the Statement of Need, but it is not a clear review of the state of the art.

If there is a reason for merging these two sections, please let me know and we can discuss things here 😄.

 There exist multiple publications on the prediction of transformation products and reaction pathways ([10.1021/acs.chemrestox.0c00224](https://pubs.acs.org/doi/10.1021/acs.chemrestox.0c00224); [10.1021/ci200542m](https://pubs.acs.org/doi/10.1021/ci200542m); [10.1016/j.ymben.2021.11.009](https://doi.org/10.1016/j.ymben.2021.11.009);) - it would be great if the section could give a small overview and argue why BioTransformer was chosen in particular.

**Comment by rickhelmus** [comment]
Thank you for your suggestions.

While many tools are available, we specifically selected BioTransformer since (1) it allows prediction of TPs formed by pathways occurring in the environment, (2) is freely available and open-source and (3) allows good integration in automated workflows for batch predictions. This is now highlighted in the main text and the caption for Table 1. Furthermore, we clarified that future extension with other prediction tools is possible. Finally, we made the following improvements to Table 1:
-	The algorithms are highlighted if they are implemented or interfaced in patRoon
-	CTS was added as example TP prediction tool
-	Suspect screening of predicted or known TPs is now split over two rows to improve readability
-	Several minor textual improvements

I just triggered a new PDF build: [link](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04029/joss.04029/10.21105.joss.04029.pdf). (unfortuantely, there is now a page break which I cannot reproduce locally, I guess that's something to fix for later...).
