### ISSUE TITLE
[JOSS Review]: Document option to use SAFD

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#44]
In the documentation, there is a line describing the options that have to be set in order to use the external dependencies - there is none for SAFD though. Is that intentional? Or hos can SAFD be used with patRoon?

**Comment by rickhelmus** [comment]
Hello,

Which part of the documentation are you referring to?

Having said that, to quote the reference manual:
> This functionality is still experimental.

In other words: the interface is still WIP, this is mainly because the SAFD interface and functionality itself is still evolving and its computational requirements are _significantly_ higher than other algorithms. So perhaps it is a bit intentional that currently the usage of SAFD is not 'advertised' as much throughout the documentation. (this doesn't take away that I think it's an interesting algorithm though 😃)

However, to use it: (again see `?findFeaturesSAFD`): 

> In order to use SAFD, please make sure that its julia packages are installed and you have verified that everything works, e.g. by running the test data.

So, in order to use it, first install it independently through `julia`. This should be enough, as `patRoon` is basically only calling a short `julia` script to run SAFD. Hence, as long `julia` is there with SAFD installed, there is no need to set any other path options etc.

**Comment by hechth** [comment]
Okay cool - thank you very much for making this clear :)
