### ISSUE TITLE
Error during findFeatures() and optimizeFeatureFinding()

### ISSUE THREAD

**Issue by akogler** [rickhelmus/patRoon#53]
We are running patRoon via a container (set up via the command below) on our university’s HPC cluster.
```
singularity pull docker://patroonorg/patroonrs
```
We have attempted to run the following two commands:
```
fListOptAll <- findFeatures(anaInfo, "openms", noiseThrInt = 22800, chromSNR = 15.85, localRTRange = 32.912, localMZRange = 21.22368, intSearchRTWindow = 1, chromFWHM = 15, mzPPM = 11.4, minFWHM = 9, maxFWHM = 52)
ftOpt <- optimizeFeatureFinding(anaInfoFopt, "openms", pSetFeatures, parallel = TRUE, maxIterations = 10, paramRanges = list(noiseThrInt = c(500,Inf)))
```
For the feature finding optimization, we have tried to run it with `parallel = FALSE` and with `parallel = TRUE` with parameters specified for parallelization using the `future` package in a few different ways as follows:
```
future::plan('multisession', workers = 8)
future::plan('multisession', workers = 2)
future::plan('multisession', workers = 4)
future::plan(cluster, workers = 2)
future::plan(sequential)
```

In all cases, we get the following error message:
![image (3)](https://user-images.githubusercontent.com/32507456/179819977-7516d284-88da-4892-9252-1067ac4c811d.png)

I've attached the full script that we are trying to run as a text file for reference. No logs are generated when we attempt to run the code, so we don’t have additional details to share. We would appreciate any suggestions for how we might resolve this issue! Thank you!
[FeatureFindingSherlock.txt](https://github.com/rickhelmus/patRoon/files/9143651/FeatureFindingSherlock.txt)

**Comment by rickhelmus** [comment]
Hello,

I just tried to run your script with Docker and it seems to be running fine. However, I couldn't run it with Singularity and your data so I tested with the example dataset from patRoonData instead. Perhaps you could try the following to find out more where the problem comes from:
1) Run it directly via Docker (maybe locally if your HPC doesn't allow so)
2) Run with the patRoonData example set instead of your data (e.g. `anaInfo <- patRoonData::exampleAnalysisInfo()`)
3) Check the log files in your project directory that should be generated after running your `findFeatures()` command. These may give hints why OpenMS is failing.

Thanks,
Rick

**Comment by romxero** [comment]
Hi All,

The issue was found to have actually been a library issue for OpenMS in the Singularity container. 
The dynamic library was : libQt5Core.so.5. 
I found this issue to only affect Singularity versions < 3.9. Versions >= 3.9 were unaffected.

The solution was found on an fmriprep github issue ticket:
https://github.com/nipreps/fmriprep/issues/2534

This was ran inside of a sandbox of the container, and it fixed the issue:
`strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`


A Singularity definition file with fix, and static LD_LIBRARY_PATH, based on patroonrs docker image is here:
https://github.com/romxero/patroonOpenmsSingularity/blob/main/Singularity

Pre fix:
```
Singularity> ldd `which OpenMSInfo`
	linux-vdso.so.1 (0x00007ffc0f3bf000)
	libOpenMS.so => /usr/lib/libOpenMS.so (0x00007f6dbfe2b000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f6dbfddf000)
	libQt5Core.so.5 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6dbfbfd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6dbfbe2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6dbf9ee000)
	libOpenSwathAlgo.so => /usr/lib/libOpenSwathAlgo.so (0x00007f6dbf7c7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6dbf7ab000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6dbf7a5000)
	libQt5Network.so.5 => /lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f6dbf5e4000)
	libQt5Core.so.5 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6dbf493000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6dbf470000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6dc24e6000)
	libQt5Core.so.5 => not found
```

Post-fix:
```
Singularity> ldd `which OpenMSInfo`
	linux-vdso.so.1 (0x00007fff65fcf000)
	libOpenMS.so => /usr/bin/../lib/libOpenMS.so (0x00007fd477a5d000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fd477a11000)
	libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fd4774c8000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd4772e6000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd4772cb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd4770d9000)
	libOpenSwathAlgo.so => /usr/bin/../lib/../lib/libOpenSwathAlgo.so (0x00007fd476eb0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd476e94000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd476e8e000)
	libQt5Network.so.5 => /lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fd476ccd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd476b7e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd476b5b000)
	libicui18n.so.66 => /lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007fd47685a000)
	libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007fd476674000)
	libpcre2-16.so.0 => /lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007fd4765f1000)
	libdouble-conversion.so.3 => /lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007fd4765db000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd4764b2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd47a118000)
	libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007fd4749ef000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd47497c000)
```

Through traceback() I got the hint of what was going on:

```
> traceback()
12: system2(cmd, sapply(args, shQuote), ...)
11: executeCommand(getCommandWithOptPath("FeatureFinderMetabo", "OpenMS"), 
        stdout = TRUE, stderr = TRUE)
10: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
        classes)) tryInvokeRestart("muffleWarning"))
9: suppressWarnings(executeCommand(getCommandWithOptPath("FeatureFinderMetabo", 
       "OpenMS"), stdout = TRUE, stderr = TRUE))

```

I'll follow up with our patron. Although I'd like to believe that this should be closed.

**Comment by rickhelmus** [comment]
Hi,

Thanks for the update and thanks for sharing (this interesting...) fix.
