### ISSUE TITLE
Suggestion: newProject(): Add remove button to Analyses/Generate analysis information/Load in script

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#60]
Hi,

is there a reason, why the "Remove" button is only available when using "From new csv file", when loading the analyses?
Otherwise I think this feature would also be useful for the "Load in script" option.

To make it available instead of:

https://github.com/rickhelmus/patRoon/blob/4e04f926a9b000c7eaa8332575a5eb1c462cf72d/R/project-tool.R#L1336-L1338

I suggest:
```
 observeEvent(input$generateAnaInfo, { 
     shinyjs::toggle("removeAnalyses", condition = input$generateAnaInfo %in% c("table", "script")) 
 }) 
```

Kind regards

Leon

**Comment by rickhelmus** [comment]
Hi Leon,

While this would be nice, this is currently not supported and also not as straightforward to implement. The reason is that the `generateAnalysisInfo()` function scans whole directories and creates the information for all the found analyses at once. Personally I often put a few additional lines of R code in the generated script to customize the `data.frame` as needed.

**Comment by rickhelmus** [comment]
Hi Leon,

Thanks ;-) I guess this could lead to a long assignment lines with many samples, but this is probably not what many people would be bothered with. Would you mind making a PR? Then I'll merge it in :-)
