### ISSUE TITLE
Error: newProject(): General/Insert code into/Current file does not work

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#62]
Hi, 

I was trying the option: _General/Insert code into/Current file_ and got the following error:

![image](https://user-images.githubusercontent.com/68274160/207313903-63f673b1-dda1-4775-8353-061b7faa5ebe.png)

In my working directory was an earlier `.Rproj` and `process.R` file, which I thought would be edited or what does _Current file_ refer to?

Kind regards

Leon

**Comment by rickhelmus** [comment]
The current file option adds the generated script code in the current active document open in RStudio, instead of making a new (process.R) script.

This is something I added ages ago but never got much attention, so thanks for checking it out as over time it stopped working. It should be working now again :-)
